name: CI/CD for To-Do App
 
on:

  push:

    branches:

      - main
 
jobs:

  build-and-deploy:

    runs-on: self-hosted
 
    steps:

      - name: trivial script

        run: |
          pwd
          ls -alF
          free -h


 




 
